### ISSUE TITLE
Separate repositories

### ISSUE THREAD

**Issue by amihaiemil** [victorrentea/training#1]
Having all the code in a literal bitbucket repository doesn't help much. 

I would separate the trainings into their own repositories. Or better yet, start a pet project where you can use your ideas and maybe ilustrate them via blog posts.

I found design patterns and best OOP practices to be most visible in components such as REST api clients or data parsers/animators (json, xml, yaml, you name it). Even though the market is filled with such components, they are usually messy with very little OO principles applied, so there is enough room for new competitors :)

For instance, it would be nice to have a decent XML parser which does not rely on JAXB and implementations such as xml-apis and xerces (which, for some reason, tend to cause messy conflicts once they are deployed on a Java EE platform)

**Comment by victorrentea** [comment]
It's on my todo list.

But in the end it's easier this eay for me during the classes: the trainees
only need to clone one repo.
And I am constantly moving things around. It's not a tidy "state of the
art" repo,I admit, but most of my typical exercises are there, for anyone
interested.

About the pet project, what I usually do at a Spring course, is I start
from start.spring.io and I build towards the specific needs of the
trainees, copyin things from other projects there


By the way: many projects can be undone (using the "undoner" project), and
some lines magically dissapear from the checked out code.

Thank you very much for your interest and suggestions!

Victor Rentea
Independent Technical Trainer, Lead Architect at IBM
www.victorrentea.ro
(+4) 0720019564

PS: Written on a tiny device. Please excuse any tpyos and abbrev

**Comment by amihaiemil** [comment]
@victorrentea I see. 

I always thought start.spring.io should have the option of creating a Github repo directly, rather than making you download a ``.zip`` :( 

jhipster does it pretty elegantly; a few commands and your github repo is up and running (even though the code and project structure are rather ugly)

**Comment by victorrentea** [comment]
Yeah.. It's somethibg you could suggest to the spring team. :)

Personally, I'd love it to give me the pom.xml. I always forget to add one
or two features on start.spring.io

As for jhipster... If you want to go to markwt super duper fast, ok... But
I personally like to have my people understand the how Spring works, and
WHY it's like that. Learning even more frameworks can make it harder to
become a good softw engineer. You're farther away from where things get
done..


Victor Rentea
Independent Technical Trainer, Lead Architect at IBM
www.victorrentea.ro
(+4) 0720019564

PS: Written on a tiny device. Please excuse any tpyos and abbrev

**Comment by amihaiemil** [comment]
@victorrentea Just opened an issue in their repo, maybe they'll think about it. 

Anyway, closing here for now :)
